# Default values for rosa_uplift lab.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployer:
  domain: REPLACEME-OPENSHIFT_DOMAIN-uplift
  apiUrl: https://api.cluster.opentlc.com:6443

ingressgatway_url_path: https://localhost

roadshow_vms:
  namespace: windows-vms
  route: vms
  runStrategy: "Manual"
  evictionStrategy: "None"
  machineType: q35
  imageUrl: http://s3.us-east.cloud-object-storage.appdomain.cloud/roadshowocpvirt
  dataVolumes:
  - name: database
    size: 16Gi
  - name: winweb01
    size: 90Gi
  - name: winweb02
    size: 90Gi
  massVms:
    count: 20
    namespace: massvm
