---
apiVersion: v1
kind: Namespace
metadata:
  name: wksp-{{ .Values.username }}
  annotations:
    openshift.io/description: "Workspace Namespace"
    openshift.io/display-name: "Workspace"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: wksp-edit-{{ .Values.username }}
  namespace: wksp-{{ .Values.username }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.username }}
