---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: loki-store
  namespace: netobserv
spec:
  resources:
    requests:
      storage: 10G
  storageClassName: ocs-external-storagecluster-ceph-rbd
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
